# action.yml
name: 'LÖVE Build'
author: 'Nathan Hartland <@nhartland>'
description: 'Action for building LÖVE project distributables (Win32/Mac/love)'
branding:
  icon: 'heart'
  color: 'blue'
inputs:
  app_name:
    description: 'Name of the application to be built'
    required: true
    default: 'love-build-app'
  love_version:
    description: 'Version of LÖVE to be used in building the application'
    required: true
    default: '11.3'
  enable_loverocks:
    description: 'Flag activating loverocks support'
    default: false
  source_dir:
    description: 'Directory containing `main.lua`. By default the GA workspace (root of cloned repository).'
    default: ${{ github.workspace }}
  build_dir:
    description: 'Directory where the intermediate build files are stored. By default the GA workspace (root of cloned repository).'
    default: ${{ github.workspace }}/love-build
  result_dir:
    description: 'Directory where the built distributables should be located. By default the GA workspace (root of cloned repository).'
    default: ${{ github.workspace }}
outputs:
  love-filename: 
    description: 'Filename (in result_dir) of built love file'
  win32-filename: 
    description: 'Filename (in result_dir) of built win32 application'
  macos-filename: 
    description: 'Filename (in result_dir) of built macos application'
runs:
  using: 'docker'
  image: 'Dockerfile'
